# Generated by Django 6.0.2 on 2026-04-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_remove_customuser_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DEPT_HEAD', 'Department Head'), ('UNIT_HEAD', 'Unit Head'), ('SUPERVISOR', 'Supervisor'), ('HR', 'HR'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
